---
- hosts: all
  become: true
  gather_facts: True
  vars:
    update: true
    upgrade: true
  tasks:
    - include_tasks: common.yml

- hosts: apps
  become: true
  tasks:
    - include_tasks: apps.yml

- hosts: lbs
  become: true
  tasks:
    - include_tasks: lbs.yml

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
